version: '3'
services:
  dev-php-apache:
    build:
      context: ./docker/dev/apache
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8080:80"
  dev-php-cli:
    build:
      context: ./docker/dev/php-cli
      dockerfile: Dockerfile
    volumes:
      - ./app:/app